name: hackathonnasa
description: Projeto realizado para o Hackathon da Nasa

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobx: ^1.2.1
  flutter_mobx: ^1.1.0
  provider: ^4.1.2
  cupertino_icons: ^0.1.3
  firebase: ^7.3.0
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^1.1.0
  build_runner: ^1.10.0

flutter:

  uses-material-design: true